name=input("what is your name?")
print("my name is"+" "+name+"," "I am basically from" )
place=input("You are From Which State?")
print(place+" "+"but lives in")
location=input("Currently where are you staying")
print(location+" "+"for around 13 year's now.")
married=input("Are You Married? ")
print("I am"+" "+married+",")
childrens=input("your baby is boy or girlavesh")
print('with a baby'+' '+childrens)
age=input("How old are him/her? ")
print("who is "+age+" "+"year old"+".")
qualification=input("What is your Qualification")
print("I have done my"+" "+qualification+" "+"in")
subject=input("Which subject you have studied")
print(subject+" "+"from")
university=input("Which University you have studied")
print("back in")
year=input("which year")
print(year+" "+".")
print("I do hold")
exp=input("How many years of experience you have")
print(exp+" "+"years of experience in")
industry=input("Which industry you have worked")
print(industry+" "+"industry as")
post=input("what is your post")
print(post+" "+"."+"I am Presently working with a Company named")
company=input("What is your company name?")
print(company+" "+"based out of ")
country=input("your company is based which country?")
print(country)



