name=input("what is your name ")
state=input("where are you from")
current_city=input("currently where are you staying")
years=input("how long are you staying here")
marriage=input("are you married or single")
child=input("do you have boy or girl")
age=input("how old her\\him")
qualification=input("what is your qualification")
subject=input("which subject you have studied")
university=input("which university you have studied")
passed=input("in which year you have passed out")
experience=input("how many years of experience you have")
type=input("what type of industry you have working")
post=input("what is your post")
company=input("what is your company name")
country=input("which country based company")
print("my name is"+" "+name+","+"i am basically from"+" "+state+" "+"but lives in"+current_city+"for around"+" "+years+" "+"now."+" ")
